### ISSUE TITLE
PhantomJs is too big for dependencies

### ISSUE THREAD

**Issue by vandeput** [judgels/judgels-web#2]
Results of investigation:
- Yes, phantomjs build is too long.
- Not only need to remove phantomjs-prebuilt, but also karma-phantomjs-launcher
- But then again, it would better if we can just suggest to install PhantomJS beforehand?

**Comment by kevinluvian** [comment]
test comment github integration

**Comment by kevinluvian** [comment]
test comment lagi

**Comment by vandeput** [comment]
Eh, for this specific issue, I will just create PR modifying README.md to suggest to install PhantomJS right....
